// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.SachDbContext;

#nullable disable

namespace _1.DAL.Migrations
{
    [DbContext(typeof(DbSach))]
    partial class DbSachModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1.DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HinhThucBia", b =>
                {
                    b.Property<Guid>("idBia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idBia");

                    b.ToTable("hinhThucBias");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IDHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<Guid>("idKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDHoaDon");

                    b.HasIndex("idKhachHang");

                    b.HasIndex("idNhanVien");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IDHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHDCT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<Guid>("idHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDHoaDonChiTiet");

                    b.HasIndex("idHoaDon");

                    b.HasIndex("idSanPham");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid>("IDKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("IDNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaCHi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("IDNhaCungCap");

                    b.ToTable("nhaCungCaps");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.NXB", b =>
                {
                    b.Property<Guid>("IDNXB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNXB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNXB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("IDNXB");

                    b.ToTable("nXBs");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("IDsanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<Guid>("IdTacGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<Guid>("idHinhThucBia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idNXB")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idNhaCungCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idTheLoai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDsanPham");

                    b.HasIndex("IdTacGia");

                    b.HasIndex("idHinhThucBia");

                    b.HasIndex("idNXB");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idTheLoai");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.TacGia", b =>
                {
                    b.Property<Guid>("idTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("idTacGia");

                    b.ToTable("tacGias");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.TheLoai", b =>
                {
                    b.Property<Guid>("IDTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTheLoai");

                    b.ToTable("theLoais");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("idKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.NhanVien", "NhanVien")
                        .WithMany("hoaDons")
                        .HasForeignKey("idNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("idHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.SanPham", "SanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.SanPham", b =>
                {
                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.TacGia", "TacGia")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.HinhThucBia", "HinhThucBia")
                        .WithMany("SanPhams")
                        .HasForeignKey("idHinhThucBia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.NXB", "NXB")
                        .WithMany("SanPhams")
                        .HasForeignKey("idNXB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("SanPhams")
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Ban_Sach._1.DAL.Models.TheLoai", "TheLoai")
                        .WithMany("SanPhams")
                        .HasForeignKey("idTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThucBia");

                    b.Navigation("NXB");

                    b.Navigation("NhaCungCap");

                    b.Navigation("TacGia");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("_1.DAL.Models.NhanVien", b =>
                {
                    b.Navigation("hoaDons");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HinhThucBia", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.NXB", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.TacGia", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Du_An_Ban_Sach._1.DAL.Models.TheLoai", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
